### ISSUE TITLE
Does ipv4.nknlabs.io still work?

### ISSUE THREAD

**Issue by Wooyme** [nknorg/nkn-sdk-js#105]
Every connection to `wss://xxx-xxx-xxx-xxx.ipv4.nknlabs.io` failed, with VPN or without.When I try to ping the address,it returns Name or service not known

**Comment by yilunzhang** [comment]
`ipv4.nknlabs.io` is just a name server that resolves `A-B-C-D.ipv4.nknlabs.io` to `A.B.C.D`. Our side always works, but sometimes (like now) the domain name provider might block it because some of the mapped IP address were associated with scammer (because VPS recycle IP address). We will try to get it unblocked

**Comment by gabriellemon** [comment]
Just to confirm, if clients were using their own RPC seed node this wouldn't matter right?

**Comment by yilunzhang** [comment]
> Just to confirm, if clients were using their own RPC seed node this wouldn't matter right? Referencing prior post: [#99 (comment)](https://github.com/nknorg/nkn-sdk-js/issues/99#issuecomment-1159560287)

For the wallet part yes, because wallet only talks to rpc node.

However, for the client part, it depends on whether sdk is running in a context that requires https/wss. NKN client will try to get nodes through RPC seed node, and then connect to those nodes directly. If a NKN client is running in a context that requires https/wss, then wss has to be used in the second part (establish direct connection to node), and it will require node to have a valid domain + certificate. In this case, if node owner does not provide its own certificate + domain, the default one (ipv4.nknlabs.io) will be used, and client will be affected.

There are many parties involved in this issue that we cannot control (browser restrictions, domain provider), so my suggestion is to use NKN client in context that does not require https/wss whenever possible, like browser extension, nodejs, electron, ipfs site, http site, etc so certificate and domain will never be used at all.

**Comment by yilunzhang** [comment]
We have changed the default cert domain to three new domains in https://github.com/nknorg/nkn/pull/910. There should be no more single point of failure when one or two of them have problems. It will be included in the next release. Nothing on the SDK side need to be done, only nodes need to upgrade.

I'm closing this issue as this domain will no longer be used. Feel free to continue the discussion or reopen if there is more problems in the next version.
