### ISSUE TITLE
Too many workers spawn

### ISSUE THREAD

**Issue by losnappas** [nknorg/nkn-sdk-js#22]
Hi,

Since the latest version, 1.1.3, nkn-sdk with multiclient `worker: true` spawns 8 workers, instead of 4, in my testing.

Something's spawning them twice, I guess..?

If you go into Firefox `about:debugging` you can see active workers.

**Comment by yilunzhang** [comment]
That's right, because each client will now create a wallet for making rpc requests. But those wallet workers are rarely used unless the client is sending transactions crazily (so worker will sign transactions).

Do you think there is any problem for that? The optimal number of workers should typically be `2 x numCores`: https://developer.mozilla.org/en-US/docs/Web/API/NavigatorConcurrentHardware/hardwareConcurrency and 8 should be a typical value for modern CPU. And I've only heard people complaining about having hundreds of workers causes performance overhead.

**Comment by losnappas** [comment]
It's probably not major a problem. However, on older phones it's going to be over the optimal.

Problems would become more apparent when you open more browser tabs, though. 8x workers for each tab is gonna stack up quick. `SharedWorker` is still something to consider.

Another thing I noticed is that the `blob:` urls for the workers are different for each worker since 1.1.3, whereas they all shared one url before. Setting up the worker blob and calling `createObjectURL` just once should be an easy optimization.

**Comment by yilunzhang** [comment]
In the next version, client created wallet will no longer create worker, that should remove half of the workers.

> SharedWorker is still something to consider.

We will probably not using SharedWorker by default since the security of SharedWorker purely depends on the security of the origin site. But if a site is fairly confident about its security and want to use Shared Worker, they should be able to use it through the worker factory or a layer of wrapper.

> Another thing I noticed is that the blob: urls for the workers are different for each worker since 1.1.3, whereas they all shared one url before. Setting up the worker blob and calling createObjectURL just once should be an easy optimization.

Hmm, I'm not sure how I can do it given how we use worker now https://github.com/nknorg/nkn-sdk-js/tree/master/src/worker Would that be a problem if each worker has its own blob?

**Comment by losnappas** [comment]
> they should be able to use it through the worker factory or a layer of wrapper.

I don't think anyone is going to be going through such lengths unless you present it in gift wrap. Perhaps it's best keep the worker disabled by default, like it is now. Wasm version works fast enough, for the usual suspects.

Each object URL of a blob url takes memory, as far as I know, but we're talking bytes here. It used to all use one url in 1.1.2, so I thought something was mixed up there.

**Comment by yilunzhang** [comment]
> It used to all use one url in 1.1.2, so I thought something was mixed up there.

That's strange because I don't think v1.1.3 changed anything related to worker, except for that each client will create a wallet that will also create web worker if client use it. In 1.1.4 those wallets will not create workers anymore, so in theory it should be the same as v1.1.2.

**Comment by losnappas** [comment]
Dunno. Could be that something's changed in Firefox? Either way, it's probably not worth the effort to go chasing that.
