### ISSUE TITLE
Will nodes be allocated by geo location?

### ISSUE THREAD

**Issue by BlindingDark** [nknorg/nkn-sdk-js#64]
Hello, I am trying to use nkn client to transfer files.
I noticed that most of the IP address of websocket are from US, such as "wss://3-137-144-60.ipv4.nknlabs.io:30004". (3.137.144.60 is the IP, I guess)
But my local network is in China, so how can it be allocated to a closer node?

I noticed that I can specify the `rpcServerAddr`. So, if I set this parameter to a closer rpc server address, will it improve the address allocation? 
Or, can I build a nkn node by myself? So that it can be allocated to this node.

**Comment by yilunzhang** [comment]
Because nkn client uses an overlay network, the actual node used for transmission only depends on your client address (identifier and public key) and cannot be changed because this is used for routing. If you connect to nodes of your choice, messages sent to you cannot be delivered because no one knows which node your client is connected to.

Changing `rpcServerAddr` will not change the node a client connects to. RPC node is only used when creating a client to get the actual node he should connect to.

Are you using sessions from multiclient? We have been using it in China and the speed is OK most of the times (a few hundred KB/s).

If you want to choose service node and you can use Golang in your client environment, you can consider using [nkn-tuna-session](https://github.com/nknorg/nkn-tuna-session), where you can filter relay node by region. It is single hop relay, so you will get much better performance (lower latency, higher throughput) at the cost of some tokens.

**Comment by BlindingDark** [comment]
> Are you using sessions from multiclient? 
Yes, sender use javascript (browser) and receiver use golang.

> a few hundred KB/s
I can only reach about 40 KiB/s here.

**Comment by yilunzhang** [comment]
What's the sessionConfig you are using? Have you tried increasing mtu like here: https://github.com/nknorg/nftp-js/blob/master/main.js

**Comment by BlindingDark** [comment]
> Have you tried increasing mtu

Thanks, I will try it.
By the way, Do I also need to set `mtu` when I use nkn-tunnel?  Seems that the default value of the mtu is 0, what does 0 mean?
https://github.com/nknorg/nkn-tunnel/blob/master/bin/main.go#L36

**Comment by yilunzhang** [comment]
In general you don't need to. The reason it might be useful in js is because browser has slower performance (in everything), so increasing mtu can reduce cpu overhead (and could potentially increase throughtput) at the cost of higher latency. For Go implementation CPU is more than enough to do anything, so typically you don't need to change mtu.

0 mtu means using the default value, which is 1024 for non-tuna mode and 1300 for tuna mode.

**Comment by BlindingDark** [comment]
After recent experiments, I found that there are many logs of connection timeout.
For example, this is the part of log on the receiver side.

```
21/02/06 22:57:42 read tcp 192.168.1.195:43624->34.219.147.132:30002: read: connection reset by peer
2021/02/06 22:57:42 Reconnect in 500 ms...
2021/02/06 22:57:55 read tcp 192.168.1.195:59468->13.58.123.150:30002: i/o timeout
2021/02/06 22:57:55 Reconnect in 500 ms...
2021/02/06 22:57:59 read tcp 192.168.1.195:51384->100.25.248.73:30002: i/o timeout
2021/02/06 22:57:59 Reconnect in 500 ms...
2021/02/06 22:58:01 read tcp 192.168.1.195:59888->13.58.123.150:30002: i/o timeout
2021/02/06 22:58:01 Retry in 500 ms...
2021/02/06 22:58:01 read tcp 192.168.1.195:43914->34.219.147.132:30002: read: connection reset by peer
2021/02/06 22:58:01 Reconnect in 500 ms...
2021/02/06 22:58:03 read tcp 192.168.1.195:51962->100.25.248.73:30002: read: connection reset by peer
2021/02/06 22:58:03 Retry in 500 ms...
2021/02/06 22:58:20 read tcp 192.168.1.195:59948->13.58.123.150:30002: read: connection reset by peer
2021/02/06 22:58:20 Reconnect in 500 ms...
2021/02/06 22:58:21 read tcp 192.168.1.195:44110->34.219.147.132:30002: read: connection reset by peer
2021/02/06 22:58:21 Reconnect in 500 ms...
2021/02/06 22:58:24 read tcp 192.168.1.195:46320->204.236.210.197:30002: read: connection reset by peer
2021/02/06 22:58:24 Reconnect in 500 ms...
```

Config:

```golang
config := &nkn.ClientConfig{
			SeedRPCServerAddr: sdk.NewStringArrayFromString(seedRpcServerAddr),
			SessionConfig: &ncp.Config{
				MTU: 16000,
			},
			MinReconnectInterval: 500,
			MaxReconnectInterval: 500,
		}
```

It will reconnect after receiving some data, so the average speed is very slow, even though the speed can reach 200 KiB/s during data reception.

**Comment by BlindingDark** [comment]
> only depends on your client address (identifier and public key)

So I randomly changed a lot of identifiers, and finally got an address connected to the nearly node.
Now the speed can reach about 200 KiB/s.
